name: AutoTests (manual cross-browsers)

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, firefox]

    container: cypress/browsers:node-22.0.0-chrome-131.0.0-edge-131.0.0-firefox-133.0.0

    env:
      CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
      CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
      CYPRESS_USER_NAME: ${{ secrets.CYPRESS_USER_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Run Cypress (${{ matrix.browser }})
        run: |
          echo "Running on ${{ matrix.browser }}"
          npx cypress run \
            --browser ${{ matrix.browser }} \
            --headless \
            --spec "cypress/e2e/**/*.cy.js"
