name: AutoTests (manual)

on:
  workflow_dispatch:

jobs:
  run-cypress:
    runs-on: ubuntu-latest

    env:
      # Settings > Secrets and variables > Actions
      CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
      CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
      CYPRESS_USER_NAME: ${{ secrets.CYPRESS_USER_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run Cypress (Chrome)
        run: |
          echo "Running all specs on Chrome"
          npx cypress run --browser chrome --headless --spec "cypress/e2e/**/*.cy.js"
